config/routes.rb
SimpleCommerce::Application.routes.draw do

   root :to => "users#sign_in"
   resources :orders
   resources :users
   resources :products
   match '/view/:id' => 'orders#view', via: :get, as: :view_order
   match 'list/' => 'orders#list', via: :get, as: :list_order
   match 'authenticate/' => 'users#authenticate', via: :post, as: :user_authenticate
   match 'destroy/' => 'users#destroy', via: :delete, as: :user_logout

end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :order_products
  has_many :products, :through => :order_products 
  belongs_to :user
  
  def self.today
    self.where("created_at >= ?", Time.zone.now.beginning_of_day).order(:created_at)
  end
  
  def self.this_week
   self.where('created_at >= ?', 1.week.ago).order(:created_at)
  end
  
  def self.this_month
    self.where(:created_at => Time.now.beginning_of_month..Time.now.end_of_month).order(:created_at)
  end
  
  def self.current_status
    self.status
  end
  
  def self.total_on(date)
    where("date(created_at) = ?",date).sum(:total_price)
  end
end

app/models/order_product.rb
class OrderProduct < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :order_products
  has_many :orders, :through => :order_products
  validates_presence_of :title, :price
  validates :price, numericality: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  attr_accessible :email, :full_name, :password, :password_confirmation
  validates_presence_of :password, :email, :on => :create
  validates_uniqueness_of :email, :on => :create
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  has_many :orders

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  protected
  def authenticate_user!
    unless session[:user_id]
      redirect_to root_url, :notice => 'if you want to add a notice'
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_filter :authenticate_user!, :only => [ :edit, :index, :list, :view, :destroy ]
  def index
    @order_today = Order.today
    @order_this_week = Order.this_week
    @order_this_month = Order.this_month
    render :layout => false
  end

  def edit
    Order.find(params[:id]).update_attributes(:status => true)
    redirect_to list_order_path
  end

  def create
   session[:user_id] = params[:user]
   total_price = Product.sum(:price, :conditions =>{:id => params[:ids]})
   order = Order.create()
   params[:ids].each { |p_id| order.order_products.create(:product_id => p_id ) }
   order.update_attributes(:total_price => total_price, :item_count => params[:ids].count)
      if order.save
        if request.xhr?
          flash[:notice] = "Order Created"
          flash.keep(:notice) # Keep flash notice around for the redirect.
          render :js => "window.location = #{list_order_path.to_json}"
        end
      end
   redirect_to list_order_path
 end
 
 def list
  @orders = Order.find(:all, :order=>"created_at DESC")
 end

 def view
  @order = Order.find(params[:id])
  @line_items = @order.products
 end

 def destroy
   Order.find(params[:id]).destroy
   redirect_to list_order_path
 end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :authenticate_user!

 def index
    @products = Product.find(:all, :order=>("created_at DESC"))
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        flash[:notice] = "New product added"
        format.html { redirect_to products_path, notice: 'product was successfully created.' }
      else
        flash[:notice] = "Form is invalid"
        format.html { render action: "new" }
      end
    end
  end
  def update
    @product = Product.find(params[:id])
    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to products_path, notice: 'product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

 def destroy
   Product.find(params[:id]).destroy
   redirect_to products_path
 end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    respond_to do |format|
      if @user.save
        flash[:notice] = "New user added"
        format.html { redirect_to orders_path, notice: 'User was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end
  
  def sign_in
  end
  
  def authenticate
  user = User.find_by_email(params[:user][:email])
  p user
  if user && user.authenticate(params[:user][:password])
    session[:user_id] = user.id
    redirect_to orders_path, :notice => "Logged in!"
  else
    flash[:danger] = "Invalid email or password"
    redirect_to root_url
  end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Order</title>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />
  <%= stylesheet_link_tag    'bootstrap', media: 'all' %>
  <%= stylesheet_link_tag    'font-awesome', media: 'all' %>
  <link href="public/stylesheets/morris/morris-0.4.3.min.css" rel="stylesheet" />
  <%= stylesheet_link_tag    'custom-styles', media: 'all' %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag "http://www.google.com/jsapi", "chartkick" %>
  <%= javascript_include_tag 'jquery-1.10.2' %>
  <%= javascript_include_tag 'bootstrap.min' %>
  <%= javascript_include_tag 'morris/raphael-2.1.0.min' %>
  <%= javascript_include_tag 'morris/morris' %>
  <%= javascript_include_tag 'custom-scripts' %>
  <%= stylesheet_link_tag    'application', media: 'all' %>

</head>

<body>
    <div id="wrapper">
        <nav class="navbar navbar-default top-navbar" role="navigation">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#"><b>Easy</b>Commerce</a>
            </div>

            <ul class="nav navbar-top-links center">
               <%= button_to "Logout", user_logout_path, :method => :delete, :class => "btn btn-danger" if session[:user_id]%>
            </ul>
        </nav>
        <!--/. NAV TOP  -->
        <nav class="navbar-default navbar-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav" id="main-menu">

                    <li>
                    <i class="fa fa-dashboard"></i>
                    <%= link_to "Dashboard", orders_path%>
                    </li>
                    <li>
                    <i class="fa fa-dashboard"></i>
                    <%= link_to "Orders", list_order_path, :id =>"order-list"%>
                    </li>
					<li>
                    <i class="fa fa-dashboard"></i>
                    <%= link_to "Create Order", products_path, :id =>"order-product"%>
                    </li>
                    <li>
                    <i class="fa fa-dashboard"></i>
                    <%= link_to "Create Product", new_product_path, :id => "new-product"%>
                    </li>
                </ul>

            </div>

        </nav>
        <div id="page-wrapper" >
            <div id="page-inner">
              <%= yield %>
            </div>
         </div>

        <footer><p>All right reserved. <a href="#">SimpleCommerce</a></p></footer>

    </div>
  
 </body>

</html>

app/views/orders/index.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Order</title>
    <!-- Google Fonts-->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />
    <%= stylesheet_link_tag    'bootstrap', media: 'all' %>
    <%= stylesheet_link_tag    'font-awesome', media: 'all' %>
    <link href="public/stylesheets/morris/morris-0.4.3.min.css" rel="stylesheet" />
    <%= stylesheet_link_tag    'custom-styles', media: 'all' %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag "http://www.google.com/jsapi", "chartkick" %>
    <%= javascript_include_tag 'jquery-1.10.2' %>
    <%= javascript_include_tag 'bootstrap.min' %>
    <%= javascript_include_tag 'morris/raphael-2.1.0.min' %>
    <%= javascript_include_tag 'morris/morris' %>
    <%= javascript_include_tag 'custom-scripts' %>
</head>

<body>
    <div id="wrapper">
        <nav class="navbar navbar-default top-navbar" role="navigation">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#"><b>Easy</b>Commerce</a>
            </div>

            <ul class="nav navbar-top-links center">
                <li><%= button_to "Logout", user_logout_path, :method => :delete, :class => "btn btn-danger" if session[:user_id]%>
            </ul>
        </nav>
        <!--/. NAV TOP  -->
        <nav class="navbar-default navbar-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav" id="main-menu">

                    <li>
                    <i class="fa fa-dashboard"></i>
                    <%= link_to "Dashboard", orders_path, :class => "active-menu"%>
                    </li>
                    <li>
                    <i class="fa fa-dashboard"></i>
                    <%= link_to "Orders", list_order_path%>
                    </li>
					<li>
                    <i class="fa fa-dashboard"></i>
                    <%= link_to "Create Order", products_path%>
                    </li>
                    <li>
                    <i class="fa fa-dashboard"></i>
                    <%= link_to "Create Product", new_product_path%>
                    </li>
                </ul>

            </div>

        </nav>
        <!-- /. NAV SIDE  -->
        <div id="page-wrapper">
            <div id="page-inner">


                <div class="row">
                    <div class="col-md-12">
                        <h1 class="page-header">
                            Dashboard <small>Order Summary</small>
                        </h1>
                    </div>
                </div>
				
				
                <!-- /. ROW  -->

                <div class="row">
                    <div class="col-md-4 col-sm-12 col-xs-12">
                        <div class="panel panel-primary text-center no-boder bg-color-green green">
                            <div class="panel-left pull-left green">
                                <i class="fa fa-bar-chart-o fa-5x"></i>
                                
                            </div>
                            <div class="panel-right pull-right">
								<h3><%= @order_today.count %></h3>
                               <strong> Orders today</strong>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 col-sm-12 col-xs-12">
                        <div class="panel panel-primary text-center no-boder bg-color-blue blue">
                              <div class="panel-left pull-left blue">
                                <i class="fa fa-shopping-cart fa-5x"></i>
								</div>
                                
                            <div class="panel-right pull-right">
							<h3><%= @order_this_week.count %></h3>
                               <strong> Orders this week</strong>

                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 col-sm-12 col-xs-12">
                        <div class="panel panel-primary text-center no-boder bg-color-red red">
                            <div class="panel-left pull-left red">
                                <i class="fa fa fa-comments fa-5x"></i>
                               
                            </div>
                            <div class="panel-right pull-right">
							 <h3><%= @order_this_month.count %></h3>
                               <strong> Orders this month </strong>

                            </div>
                        </div>
                    </div>
                </div>

				<div class="row">
				<div class="col-md-12">
					<div class="panel panel-default">
						<div class="panel-heading">
							Line Chart
						</div>
						<div class="panel-body">
							<div id="morris-line-chart">
							  <%= line_chart Order.group_by_day(:created_at, format: "%B %d, %Y").sum(:total_price), {discrete: true, library: {hAxis: {title: "Date"}, vAxis: {title: "Total Price"}}} %>
                            </div>
						</div>
					</div>  
					</div>		
				</div> 
				
                       </div>

                    </div>
                </div>
                <!-- /. ROW  -->
				<footer><p>All right reserved. <a href="#">SimpleCommerce</a></p></footer>
            </div>
            <!-- /. PAGE INNER  -->
        </div>
        <!-- /. PAGE WRAPPER  -->
    </div>
 </body>

</html>

app/views/orders/list.html.erb
<%- model_class = Order -%>
			 <div class="row">
                    <div class="col-md-12">
                        <h1 class="page-header">
                            Order Listing <small>View all order and fulfill when completed</small>
                        </h1>
                    </div>
                </div> 
                 <!-- /. ROW  -->
               
            <div class="row">
                <div class="col-md-12">
                    <!-- Advanced Tables -->
                    <div class="panel panel-default">
                        <div class="panel-heading">
                             Order
                        </div>
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <thead>
                                      <tr>
                                        <th><%= "Order Id" %></th>
                                        <th><%= model_class.human_attribute_name(:status) %></th>
                                        <th><%= "Total Price" %></th>
                                        <th><%= "Created At" %></th>
                                        <th><%="Fulfill Order" %></th>
                                        <th><%="View Order" %></th>
                                        <th><%="Delete Order" %></th>
                                     </tr>
                                    </thead>
                                    <tbody>
                                      <% @orders.each do |order| %>
                                        <tr>
                                        <td><%= order.id %></td>
                                        <td><%= order.status ? "Fulfilled" : "Unfulfilled" %></td>
                                        <td><%= order.total_price %></td>
                                        <td><%= order.created_at.strftime("%m/%d/%Y") %></td>
                                        <td><%=order.status ? "Completed" : (link_to "Fulfill Order", edit_order_path(order), :class => 'btn btn-primary')%></td>
                                        <td><%=link_to "View", view_order_path(order), :class => 'btn btn-primary'%></td>
                                        <td><%= button_to t('.destroy', :default => t("helpers.links.destroy")),order_path(order), :method => 'delete', :class => 'btn btn-danger'  unless order.status %></td>
                                        </tr>
                                      <% end %>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <!--End Advanced Tables -->
                </div>
            </div>
            </div>
                <!-- /. ROW  -->
    <%=javascript_include_tag "jquery.metisMenu.js" %>

app/views/orders/view.html.erb
<%- model_class = Product -%>
			 <div class="row">
                    <div class="col-md-12">
                        <h1 class="page-header">
                            Order View <small>Lists products in current order</small>
                        </h1>
                    </div>
                </div> 
                 <!-- /. ROW  -->
               
            <div class="row">
                <div class="col-md-12">
                    <!-- Advanced Tables -->
                    <div class="panel panel-default">
                        <div class="panel-heading">
                             Product
                        </div>
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <thead>
                                      <tr>
                                        <th><%= model_class.human_attribute_name(:title) %></th>
                                        <th><%= model_class.human_attribute_name(:description) %></th>
                                        <th><%= model_class.human_attribute_name(:price) %></th>
                                        <th><%= model_class.human_attribute_name(:created_at) %></th>
                                     </tr>
                                    </thead>
                                    <tbody>
                                      <% @line_items.each do |product| %>
                                        <tr>
                                          <td><%= product.title %></td>
                                          <td><%= product.description %></td>
                                          <td><%= product.price %></td>
                                          <td><%= product.created_at.strftime("%m/%d/%Y") %></td>
                                        </tr>
                                      <% end %>
                                    </tbody>
                                </table>
                            </div>
                            <%=link_to 'Back', list_order_path, :class => 'btn btn-primary '%>
                        </div>
                    </div>
                    <!--End Advanced Tables -->
                </div>
            </div>
            </div>
                <!-- /. ROW  -->
    <%=javascript_include_tag "jquery.metisMenu.js" %>

app/views/products/_form.html.erb
			 <div class="row">
                    <div class="col-md-12">
                        <h1 class="page-header">
                            Product <small>Create / Edit your Product.</small>
                        </h1>
                    </div>
                </div> 
                 <!-- /. ROW  -->
              <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Product
                        </div>
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-lg-6">
                                  <%= form_for @product do |f| %>
                                    <% if @product.errors.any? %>
                                      <div class="alert alert-danger">
                                        <ul>
                                          <% for message in @product.errors.full_messages %>
                                            <li><%= message %></li>
                                          <% end %>
                                        </ul>
                                      </div>
                                    <% end %>
                                        <div class="form-group">
                                            <%= f.label :title%>
                                            <%= f.text_field :title, :class => 'form-control' %>
                                        </div>
                                        <div class="form-group">
                                            <%= f.label :description%>
                                            <%= f.text_area :description, :class => 'form-control', rows: 3 %>
                                        </div>
                                        <div class="form-group">
                                            <%= f.label :price%>
                                            <%= f.number_field :price, :class => 'form-control'%>
                                        </div>
                                        <%= f.submit "Submit", :class => 'btn btn-primary' %>
                                        <%= link_to "Cancel", products_path, :class => 'btn btn-default' %>
                                    <%end%>
                                </div>
                            </div>
                            <!-- /.row (nested) -->
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
                <!-- /. ROW  -->
    <%=javascript_include_tag "jquery.metisMenu.js" %>

app/views/products/edit.html.erb
<%= javascript_include_tag    "product", :media => "all" %>
<%- model_class = Product -%>
<%= render :partial => 'form' %>

app/views/products/index.html.erb
<%= javascript_include_tag "product" %>
<%- model_class = Product -%>
			 <div class="row">
                    <div class="col-md-12">
                        <h1 class="page-header">
                            Product Listing <small>Create your order here</small>
                        </h1>
                    </div>
                </div> 
                 <!-- /. ROW  -->
               
            <div class="row">
                <div class="col-md-12">
                    <!-- Advanced Tables -->
                    <div class="panel panel-default">
                        <div class="panel-heading">
                             Product
                        </div>
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <thead>
                                      <tr>
                                        <th><%= model_class.human_attribute_name(:id) %></th>
                                        <th><%= model_class.human_attribute_name(:title) %></th>
                                        <th><%= model_class.human_attribute_name(:description) %></th>
                                        <th><%= model_class.human_attribute_name(:price) %></th>
                                        <th><%= model_class.human_attribute_name(:created_at) %></th>
                                        <th><%="Choose Product" %></th>
                                        <th><%="Edit Product" %></th>
                                        <th><%="Delete Product" %></th>
                                     </tr>
                                    </thead>
                                    <tbody>
                                        <% @products.each do |product| %>
                                            <tr class="odd gradeX">
                                              <td><%= product.id %></td>
                                              <td><%= product.title %></td>
                                              <td><%= product.description %></td>
                                              <td><%= product.price %></td>
                                              <td><%= product.created_at.strftime("%m/%d/%Y") %></td>
                                              <td><%= link_to 'choose', '#', :onclick=>"check_prod(#{product.id});return false;" ,:class => 'btn btn-mini btn-primary'%> <%= check_box_tag "check_#{product.id}", product.id%></td>
                                              <td><%= link_to t('.edit', :default => t("helpers.links.edit")), edit_product_path(product), :class => 'btn btn-primary' %></td>
                                              <td><%= button_to t('.destroy', :default => t("helpers.links.destroy")), product_path(product), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger' %></td>
                                            </tr>
                                        <% end %>
                                    </tbody>
                                </table>
                            </div>
<%= link_to 'Create Order','#', :onclick=>"create_order(#{session[:user_id]});return false;" ,:class => 'btn btn-primary'%>

                        </div>
                    </div>
                    <!--End Advanced Tables -->
                </div>
            </div>
            </div>
                <!-- /. ROW  -->
    <%=javascript_include_tag "jquery.metisMenu.js" %>


app/views/products/new.html.erb
<%= javascript_include_tag "product" %>
<%- model_class = Product -%>
<%= render :partial => 'form' %>

app/views/users/sign_in.html.erb
			 <div class="row">
                    <div class="col-md-12">
                        <h1 class="page-header">
                            EasyCommerce <small>Shop eassssssssy..</small>
                        </h1>
                    </div>
                </div> 
                 <!-- /. ROW  -->
              <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Login to view Orders
                        </div>
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-lg-6">
                                  <%= form_for :user, url: user_authenticate_path do |f| %>
                                    <%if flash[:danger]%>
                                      <div class="alert alert-danger">
                                        <%= flash[:danger]%>
                                      <div>
                                    <%end%>
                                        <div class="form-group">
                                            <%= f.label :email%>
                                            <%= f.text_field :email, :class => 'form-control' %>
                                        </div>
                                        <div class="form-group">
                                            <%= f.label :password%>
                                            <%= f.password_field :password, :class => 'form-control' %>
                                        </div>
                                        <%= f.submit "Login", :class => 'btn btn-default' %>
                                        <%= link_to "Register", new_user_path, :class => 'btn btn-primary' %>
                                    <%end%>
                                </div>
                            </div>
                            <!-- /.row (nested) -->
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
                <!-- /. ROW  -->
    <%=javascript_include_tag "jquery.metisMenu.js" %>